# Site settings
# These are used to personalize your new site. If you look in the HTML files, you will see them accessed
# via {{ site.title }}, {{ site.github_repo }}, and so on. You can create any custom variable you would
# like, and they will be accessible in the templates via {{ site.myvariable }}.
title: TOP10NL help met MD
description: Testpagina om TOP10NL-help met MD te maken
theme: just-the-docs
url: https://danieltewinkel.github.io/test-top10nl-help

# Color scheme supports "light" (default) and "dark".
# color_scheme: light # Uitgezet vanwege het gebruik van een eigen kleurenschema
# Or use an own color scheme to change colours.
color_scheme: TOP10NL-help_light # Eigen gemaakt kleurenschema
# color_scheme: TOP10NL-help_dark # Bestaat wel, nog niet geconfigureerd

# Set a path/url to a logo that will be displayed instead of the title.
logo: "/images/TOP10NL-help_CMYK.svg"
# Set a path/url to a favicon that will be displayed by the browser.
favicon_ico: "/images/favicon.ico"

# Option to exclude a folder / file.
exclude:
  - aantekeningen.md
  - Top10NL Help Verkenningsvoorschriften

# By default, all Capital letters come before all lowercase letters; you can add nav_sort: case_insensitive in the configuration file to ignore the case.
nav_sort: case_insensitive

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result
  # Default: 3
  previews: 4
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 5
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# Aux links for the upper right navigation.
aux_links:
  JustTheDocs: https://just-the-docs.github.io/just-the-docs/
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Footer content: Appears at the bottom of every page's main content.
# Back to top link
back_to_top: true
back_to_top_text: "Terug naar boven"

# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; Kadaster: DPI en GI"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%e %b %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
