title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://danieltewinkel.github.io/test-top10nl-help

aux_links:
  GIThub Repository: https://github.com/DanielteWinkel/test-top10nl-help
